eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 2001
spring:
  application:
    name: eureka-client
  datasource:
      db1: # 数据源1
        jdbc-url: jdbc:mysql://localhost:3306/hami?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123.com
        driver-class-name: com.mysql.cj.jdbc.Driver
      db2: # 数据源2
        jdbc-url: jdbc:mysql://localhost:3306/hami2?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123.com
        driver-class-name: com.mysql.cj.jdbc.Driver

